- id: '1605575238274'
  alias: Evening Lights On
  description: Turn on the lights when the sun sets
  trigger:
  - platform: sun
    event: sunset
    offset: -00:35:00
  condition:
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.jen
      zone: zone.home
    - condition: zone
      entity_id: person.jared
      zone: zone.home
  action:
  - scene: scene.evening_default
  mode: single
  max: 10
- id: '1605653736019'
  alias: Notify Jen on front porch motion
  description: Motion detected on front porch
  trigger:
  - platform: state
    entity_id: binary_sensor.front_porch_cam_motion_detected
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_jen_s_phone
    data:
      title: Motion detected on front porch
      message: check it out
      data:
        clickAction: /lovelace/security
  mode: queued
  max: 10
- id: '1605756985220'
  alias: Notify Jen to unlock door when arriving home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.jen
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_jen_s_phone
    data:
      title: Welcome Home
      message: Would you like to unlock the side door?
      data:
        actions:
        - action: unlock_side_door
          title: Unlock
  mode: queued
  max: 10
- id: '1605757550925'
  alias: Unlock Side Door from Notification
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: unlock_side_door
  condition: []
  action:
  - device_id: 09fd9fbc9837218c3bfb874bd466c216
    domain: lock
    entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked
    type: unlock
  mode: queued
  max: 10
- id: '1610920141323'
  alias: Side Door Light on Motion
  description: ''
  trigger:
  - platform: state
    attribute: state
    to: 'on'
    entity_id: binary_sensor.side_door_motion
    from: 'off'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.side_door_inside_light
  mode: single
- id: '1610920273201'
  alias: Side Door Light When Clear
  description: Turn off light after no motion for 5 minutes
  trigger:
  - platform: state
    entity_id: binary_sensor.side_door_motion
    attribute: state
    for: 00:05:00
    to: 'false'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.side_door_inside_light
  mode: single
- id: '1612122170563'
  alias: Trigger Bedtime when Jen's Phone gets plugged in
  description: lights off, etc
  trigger:
  - platform: state
    entity_id: binary_sensor.moto_x4_is_charging
    to: 'on'
  condition:
  - condition: time
    after: '21:00'
  action:
  - scene: scene.bedtime
  mode: single
- id: '1612470241665'
  alias: Turn on office light when Jen is in a meeting
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.jennifers_macbook_pro_camera_in_use
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.office_light
  mode: single
- id: '1612470310204'
  alias: Turn off office light at the end of a meeting
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.jennifers_macbook_pro_camera_in_use
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.office_light
  mode: single
- id: '1612537386339'
  alias: Trigger Morning Scene at 8am
  description: ''
  trigger:
  - platform: time
    at: 08:00
  condition: []
  action:
  - scene: scene.morning
  mode: single
- id: '1613598163981'
  alias: Notify Jen on Driveway Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.driveway_cam_motion_detected
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_jen_s_phone
    data:
      title: Motion detected in driveway
      message: check it out
      data:
        clickAction: /lovelace/security
  mode: single
