- id: '1605575238274'
  alias: Evening Lights On
  description: Turn on the lights when the sun sets
  trigger:
  - platform: sun
    event: sunset
    offset: -00:35:00
  condition:
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.jen
      zone: zone.home
    - condition: zone
      entity_id: person.jared
      zone: zone.home
  action:
  - scene: scene.evening_default
  mode: single
  max: 10
- id: '1605653736019'
  alias: Notify Jen on front porch motion
  description: Motion detected on front porch
  trigger:
  - platform: state
    entity_id: binary_sensor.front_porch_cam_motion_detected
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_jen_s_phone
    data:
      title: Motion detected on front porch
      message: check it out
      data:
        clickAction: /lovelace/security
  mode: queued
  max: 10
- id: '1605756985220'
  alias: Notify Jen to unlock door when arriving home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.jen
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_jen_s_phone
    data:
      title: Welcome Home
      message: Would you like to unlock the side door?
      data:
        actions:
        - action: unlock_side_door
          title: Unlock
  mode: queued
  max: 10
- id: '1612122170563'
  alias: Trigger Bedtime when Jen's Phone gets plugged in
  description: lights off, etc
  trigger:
  - platform: state
    entity_id: binary_sensor.moto_x4_is_charging
    to: 'on'
  condition:
  - condition: time
    after: '21:00'
  action:
  - scene: scene.bedtime
  mode: single
- id: '1612537386339'
  alias: Trigger Morning Scene at 8am
  description: ''
  trigger:
  - platform: time
    at: 08:00
  condition: []
  action:
  - scene: scene.morning
  mode: single
- id: '1613598163981'
  alias: Notify Jen on Driveway Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.driveway_cam_motion_detected
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_jen_s_phone
    data:
      title: Motion detected in driveway
      message: check it out
      data:
        clickAction: /lovelace/security
  mode: single
