
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
amcrest: !include cameras.yaml
  
climate:
  - platform: radiotherm
    host:
      - !secret thermostat_ip

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

light:
  - platform: switch
    name: Kitchen Light
    entity_id: switch.kitchen
  - platform: group
    name: All Lights
    entities:
      - light.side_door_inside_light
      - light.office_light
      - light.living_room_lamp_1
      - light.kitchen_light
  
#zwave:
#  network_key: !secret zwave_key
homeassistant:
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /share
    - /share/cameras

notify:
  - name: slack_bot
    platform: slack
    api_key: !secret slack_api_key
    default_channel: !secret slack_channel
    username: house
    icon: house
