
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
amcrest: !include cameras.yaml

lovelace:
  mode: yaml

wyzeapi:
  username: !secret wyze_username
  password: !secret wyze_password
  lock: false
  switch: false
  
  
climate:
  - platform: radiotherm
    host:
      - !secret thermostat_ip

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
