## WARNING ##
# This file is auotmaticly generated, any changes
# will be overwritten.

##################################################
################  COMMON ENTITIES  ###############
##################################################

###############  input_boolean:  #################
input_boolean:
  side_door_lock_notifications:
    name: side_door Lock Notifications
  side_door_dooraccess_notifications:
    name: side_door Door Notifications
  side_door_garageacess_notifications:
    name: side_door Garage Notifications
  side_door_reset_lock:
    name: side_door reset lock

###################  script:  ####################
script:
  side_door_reset_lock:
    sequence:
      - service: script.side_door_manual_notify
        data_template:
          title: "reset"
          message: "side_door"

  side_door_reset_codeslot:
    mode: parallel
    fields:
      code_slot:
        description: The code slot to reset
        example: 1
    variables:
      # Constant used later to loop through day specific entities
      days: ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
    sequence:
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.enabled_side_door_{{ code_slot | string }}"
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.side_door_name_{{ code_slot | string }}"
          value: ""
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.side_door_pin_{{ code_slot | string }}"
          value: ""
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.notify_side_door_{{ code_slot | string }}"
      - service: input_number.set_value
        data_template:
          entity_id: "input_number.accesscount_side_door_{{ code_slot | string }}"
          value: "0"
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.start_date_side_door_{{ code_slot | string }}"
          date: >-
            {{ now().strftime('%Y-%m-%d') }}
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.end_date_side_door_{{ code_slot | string }}"
          date: >-
            {{ now().strftime('%Y-%m-%d') }} 
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.daterange_side_door_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.accesslimit_side_door_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.reset_codeslot_side_door_{{ code_slot | string }}"
      # Loop through each day of the week and reset the entities related to each one
      - repeat:
          count: 7
          sequence:
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_start_date_side_door_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_end_date_side_door_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_side_door_{{ code_slot | string }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_inc_side_door_{{ code_slot | string }}"

  side_door_refreshnodeinfo:
    description:  'Send MQTT RefreshNodeInfo command'
    sequence:
      - service: system_log.write
        data_template:
          message: "side_door_TEMPLATENUM started noderefreshinfo: {{ now() }}"
          level: debug  
      - service: mqtt.publish
        data:
          topic: 'OpenZWave/1/command/refreshnodeinfo/'
          payload: >-
            {% set node_id = state_attr('lock.side_door_lock_locked','node_id') %}
            { "node": {{ node_id }} }
          retain: true
          
###################  automation:  ####################
automation:

  - alias: reset_codeslot_side_door
    trigger:
      entity_id: input_boolean.reset_codeslot_side_door_1,input_boolean.reset_codeslot_side_door_2
      platform: state
      to: 'on'
    action:
      - service: script.side_door_reset_codeslot
        data_template:
          code_slot: "{{ trigger.entity_id.split('_')[-1] }}"

  - alias: side_door Lock Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: side_door
    condition:
      - condition: state
        entity_id: input_boolean.side_door_lock_notifications
        state: "on"
    action:
      - service: script.side_door_manual_notify
        data_template:
          title: side_door
          message: "{{ trigger.event.data.action_text }}"

  - alias: side_door User Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: side_door
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.code_slot > 0 }}"
      - condition: template
        value_template: "{{ is_state('input_boolean.notify_side_door_' + trigger.event.data.code_slot | string, 'on') }}"
    action:
      - service: script.side_door_manual_notify
        data_template:
          title: side_door
          message: "{{ trigger.event.data.action_text }} ({{ trigger.event.data.code_slot_name }})"

  - alias: "side_door Door Open and Close"
    trigger:
      entity_id: binary_sensor.fake
      platform: state
    condition:
      - condition: state
        entity_id: "input_boolean.side_door_dooraccess_notifications"
        state: "on"
      - condition: template
        value_template: "{{ trigger.from_state.state in ('on', 'off') and trigger.to_state.state in ('on', 'off') }}"
    action:
      - service: script.side_door_manual_notify
        data_template:
          title: side_door
          message: "{% if trigger.to_state.state == 'on' %}Door Opened{% else %}Door Closed{% endif %}"

  - alias: side_door Changed Code
    trigger:
      entity_id: input_text.side_door_pin_1,input_text.side_door_pin_2
      platform: state
    condition:
      - condition: template
        value_template: >-
          {{
            is_state('input_boolean.side_door_enabled_' + trigger.entity_id.split('_')[-1], 'on')
            and
            (trigger.from_state.state != trigger.to_state.state)
          }}
    action:
      - service: persistent_notification.create
        data_template:
          title: side_door LOCK MANAGER
          message: >-
            {{ 'You changed the PIN for side_door code slot ' + trigger.entity_id.split('_')[-1] + '. Please enable it in order to make it active.'}}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {{ 'input_boolean.enabled_side_door_' + trigger.entity_id.split('_')[-1] }}

  - alias: side_door Reset
    trigger:
      entity_id: input_boolean.side_door_reset_lock
      platform: state
      from: "off"
      to: "on"
    action:
      - service: script.side_door_reset_lock
      - service: input_boolean.turn_off
        entity_id: input_boolean.side_door_reset_lock

  - alias: side_door Decrement Access Count
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: side_door
    condition:
      - condition: template
        # make sure decrementing access entries is enabled 
        value_template: "{{ is_state('input_boolean.accesslimit_side_door_' + trigger.event.data.code_slot | string, 'on') }}"
      - condition: template
        # Check for Keypad Unlock code
        value_template: "{{ trigger.event.data.code_slot > 0 and trigger.event.data.action_code in (6, 19)}}"
    action:
      - service: input_number.decrement
        data_template:
          entity_id: "{{ 'input_number.accesscount_side_door_' + trigger.event.data.code_slot | string }}"
